#!/bin/bash

# esporta le variabili d'ambiente
set -a

# constants
DATA_DIR="data"
SUGGERIMENTI_DIR="suggerimenti"
LITURGIA_URL="https://www.chiesacattolica.it/liturgia-del-giorno/?data-liturgia="
LITURGIA_DIR="liturgie"
LITURGIA_FILE_BASENAME="liturgia"
SUGGERIMENTI_FILE_BASENAME="suggerimenti"
HOMEPAGE_PATH="docs/index.md"


# importing functions
source ./scripts/get_anagrafica
source ./scripts/get_next_sunday
source ./scripts/get_liturgia
source ./scripts/converti_data

# crea cartella data se non esiste
if [ ! -d "$DATA_DIR" ]; then
  mkdir $DATA_DIR
fi

# crea cartella suggerimenti se non esiste
if [ ! -d "$SUGGERIMENTI_DIR" ]; then
  mkdir $SUGGERIMENTI_DIR
fi

# crea cartella liturgie se non esiste
if [ ! -d "$LITURGIA_DIR" ]; then
  mkdir $LITURGIA_DIR
fi

# rendi eseguibili gli script
chmod +x ./scripts/*

# scarica anagrafica
# get_anagrafica > $DATA_DIR/anagrafica_canti.csv
# echo "✅ Scaricata anagrafica canti"

# scarica testi
# ./scripts/db_downloader
# echo "✅ Scaricati testi canti"

# scarica liturgia
LITURGIA_DATE=$(get_next_sunday)
#LITURGIA_DATE=20240616

liturgia_data_iso=$(date -d $LITURGIA_DATE +%Y-%m-%d)
liturgia_data_estesa=$(converti_data "$liturgia_data_iso")

get_liturgia $LITURGIA_DATE > $LITURGIA_DIR/$LITURGIA_FILE_BASENAME-$LITURGIA_DATE.txt
cp $LITURGIA_DIR/$LITURGIA_FILE_BASENAME-$LITURGIA_DATE.txt $LITURGIA_DIR/$LITURGIA_FILE_BASENAME-latest.txt

echo "📅 Data della prossima liturgia domenicale: $(date -d $LITURGIA_DATE +%d/%m/%Y)"
echo "✅ Scaricata liturgia"

# run suggeritore
./scripts/suggeritore.py

# build website homepage
./scripts/build_page

# organize files 
cp $DATA_DIR/$SUGGERIMENTI_FILE_BASENAME-latest.csv $DATA_DIR/$SUGGERIMENTI_FILE_BASENAME-$LITURGIA_DATE.csv

suggerimenti_on_archive_path="docs/archivio/$liturgia_data_estesa.md"
cp $HOMEPAGE_PATH "$suggerimenti_on_archive_path"

# clean suggerimenti on archive
line_end=$(cat "$suggerimenti_on_archive_path" | grep -n ":material-music" | cut -d: -f1)

# delete from line 1 to line line_end
tail -n +$line_end "$suggerimenti_on_archive_path" > tmp.md
mv tmp.md "$suggerimenti_on_archive_path"


echo "✅ Suggerimenti pronti"
echo "📂 Archivio aggiornato"
echo "✅ Homepage pronta"
