#!/bin/bash

# constants
DATA_DIR="data"

# importing functions
source ./scripts/get_anagrafica
source ./scripts/get_next_sunday

# crea cartella data se non esiste
if [ ! -d "$DATA_DIR" ]; then
  mkdir $DATA_DIR
fi

# rendi eseguibili gli script
chmod +x ./scripts/*

# scarica anagrafica
# get_anagrafica > $DATA_DIR/anagrafica_canti.csv
# echo "✅ Scaricata anagrafica canti"

# scarica testi
# ./scripts/db_downloader
# echo "✅ Scaricati testi canti"

# scarica liturgia
LITURGIA_DATE=$(get_next_sunday)
./scripts/get_liturgia $LITURGIA_DATE
LITURGIA_DATE=$(date -d $LITURGIA_DATE +%d/%m/%Y)
echo "📅 Data della prossima liturgia domenicale: $LITURGIA_DATE"
echo "✅ Scaricata liturgia"

# run suggeritore
./scripts/suggeritore.py