#!/bin/bash

# TODO
# verificare la corretta esecuzione del suggeritore e di qualsiasi altro comando: gestire errori

# esporta le variabili d'ambiente
set -a
#set -x

# import variables
source <(grep = scripts/config.ini)

# importing functions
source ./scripts/functions/get_anagrafica
source ./scripts/functions/get_next_sunday
source ./scripts/functions/get_next_mass_date
source ./scripts/functions/get_liturgia
source ./scripts/functions/convert_iso_to_extended_date
source ./scripts/functions/convert_iso_to_weekday
source ./scripts/functions/add_element_to_mkdocs_nav

# crea cartella data se non esiste
if [ ! -d "$PATH_DATA" ]; then
  mkdir $PATH_DATA
  echo "✅ Creata cartella data"
fi

# crea cartella liturgie se non esiste
if [ ! -d "$PATH_LITURGIE" ]; then
  mkdir $PATH_LITURGIE
  echo "✅ Creata cartella liturgie"
fi

# rendi eseguibili gli script
chmod +x ./scripts/*

# se vuoi scaricare anagrafica canti e testi canti devi usare
# db_downloader
# con le opportune istruzioni e autenticazioni
# viene eseguito da una GitHub Action una volta al mese

# genero la data di oggi in formato iso
today=$(date +%Y-%m-%d)

# scarica liturgia
liturgia_data_iso=$(get_next_mass_date "$PATH_CALENDARIO_LITURGICO" "$today" 1)
liturgia_data_yyyymmdd=$(date -d $liturgia_data_iso +%Y%m%d)
liturgia_data_estesa=$(convert_iso_to_extended_date "$liturgia_data_iso")
liturgia_weekday=$(convert_iso_to_weekday "$liturgia_data_iso")

get_liturgia "$liturgia_data_iso" "$PATH_CALENDARIO_LITURGICO" "$PATH_LITURGIE_FORMATTED" > $PATH_LITURGIA

# se get liturgia ritorna errore, esci
if [ $? -eq 1 ]; then
  echo "❌ $0: Errore durante il recupero della liturgia" >&2
  exit 1
fi

echo "📅 Data della prossima liturgia domenicale: $(date -d $liturgia_data_iso +%d/%m/%Y)"
echo "✅ Individuata liturgia"

# aggiorna canti manually selected
./scripts/get_manually_selected

# per supportare la generazione di più suggerimenti bisognerà modificare il suggeritore.py e build_page

# run suggeritore
./scripts/suggeritore.py "$liturgia_data_iso" 

# build website homepage
./scripts/build_page

# organize files 
cp $PATH_DATA/$FILE_BASENAME_SUGGERIMENTI-latest.csv $PATH_DATA/$FILE_BASENAME_SUGGERIMENTI-$liturgia_data_yyyymmdd.csv

suggerimenti_on_archive_path="docs/archivio/$liturgia_data_estesa.md"
cp $PATH_HOMEPAGE "$suggerimenti_on_archive_path"

# clean suggerimenti on archive
line_end=$(cat "$suggerimenti_on_archive_path" | grep -n ":material-music" | cut -d: -f1)

# delete from line 1 to line line_end
tail -n +$line_end "$suggerimenti_on_archive_path" > tmp.md
mv tmp.md "$suggerimenti_on_archive_path"

# new nav management: aggiungi la liturgia all'archivio
add_element_to_mkdocs_nav "mkdocs.yml" "$(date -d $liturgia_data_iso +%Y)" "archivio/$liturgia_data_estesa.md"
echo "📂 Archivio aggiornato"

echo "✅ Suggerimenti pronti"
echo "✅ Homepage pronta"
