#!/bin/bash

DATA_DIR="data"

source ./scripts/get_anagrafica

# crea cartella data se non esiste
if [ ! -d "$DATA_DIR" ]; then
  mkdir $DATA_DIR
fi

# scarica anagrafica
get_anagrafica > $DATA_DIR/anagrafica_canti.csv
echo "Scaricata anagrafica canti"

# scarica testi
# ./scripts/db_downloader

# scarica liturgia
./scripts/get_liturgia $(./scripts/get_next_sunday)
echo "Scaricata liturgia"

# run suggeritore
./scripts/suggeritore.py