authors:
  dennis:
    name: Dennis Angemi
    description: Creator
    avatar: https://2.gravatar.com/avatar/50df7f79581e52d016a68ceb62a9e6c0e8fd0404f38c339b9170bd23e0d82146?size=512
  hildegard:
    name: Hildegard AI
    description: Blogger ✨
    avatar: images/hildegard-ai-profile-pic.png
