#!/bin/bash

# Script:      extract_antifona_ingresso
# Descrizione: Questo script estrae l'antifona d'ingresso per una data specifica dal sito liturgia.silvestrini.org.
# Utilizzo:    ./extract_antifona_ingresso <data>
# Esempio:     ./extract_antifona_ingresso 2024-06-02
# Parametri:
#   <data> - La data per la quale estrarre l'antifona d'ingresso, nel formato YYYY-MM-DD.
# Requisiti:
#   - curl: per scaricare il contenuto della pagina web.
#   - scrape: per estrarre il contenuto HTML.
#   - xq: per processare il contenuto JSON.
#   - tr, sed: per pulire e formattare il testo estratto.

extract_antifona_ingresso() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <file>"
        return 1
    fi
    # check if the input is provided
    if [ -z "$1" ]; then
        echo "Please provide the date in the format YYYY-MM-DD (e.g. $0 2024-06-02)"
        return 1
    fi

    # check if the input is a valid iso date
    if ! date -d $1 > /dev/null 2>&1; then
        echo "Please provide a valid date in the format YYYY-MM-DD (e.g., $0 2024-06-02)"
        return 1
    fi

    curl -s "https://liturgia.silvestrini.org/letture/$1.html" | scrape -be ".text-justify" | xq -r '.html.body.div.div[] | {"@id" ,h3, "#text"} | select(."@id" == "div_antifona_ingresso")."#text"' | tr -d '*' | sed 's/^[ \t]*//;s/[ \t]*$//;s/[ \t]\+/ /g'


}