#!/bin/bash

# -------------------------------------------------------------------------------------------------- #
# Function: convert_iso_to_extended_date
# Description: Converts a date from ISO format (YYYY-MM-DD) to extended Italian format (DD mese YYYY).
# 
# Usage:
#   convert_iso_to_extended_date <ISO_date>
# 
# Arguments:
#   ISO_date - A date in ISO format (YYYY-MM-DD).
# 
# Output:
#   Prints the date in extended Italian format (DD mese YYYY).
# 
# Example:
#   $ convert_iso_to_extended_date 2023-10-05
#   5 ottobre 2023
# 
# Notes:
#   - The function accepts a single argument which is the date in ISO format.
#   - The function will print an error message and exit if the month is not valid.
# -------------------------------------------------------------------------------------------------- #

convert_iso_to_extended_date() {
  # input: data in formato ISO (YYYY-MM-DD)
  # output: data estesa in italiano (DD mese YYYY)

  # Accetta la data come argomento
  data="$1"

  # Estrai giorno, mese e anno
  giorno=$(echo $data | awk -F- '{print $3}' | sed 's/^0*//')
  mese=$(echo $data | awk -F- '{print $2}')
  anno=$(echo $data | awk -F- '{print $1}')

  # Converti il numero del mese nel nome del mese in italiano
  case $mese in
    "01") nome_mese="gennaio" ;;
    "02") nome_mese="febbraio" ;;
    "03") nome_mese="marzo" ;;
    "04") nome_mese="aprile" ;;
    "05") nome_mese="maggio" ;;
    "06") nome_mese="giugno" ;;
    "07") nome_mese="luglio" ;;
    "08") nome_mese="agosto" ;;
    "09") nome_mese="settembre" ;;
    "10") nome_mese="ottobre" ;;
    "11") nome_mese="novembre" ;;
    "12") nome_mese="dicembre" ;;
    *) echo "Mese non valido"; exit 1 ;;
  esac

  # Stampa la data nel formato desiderato
  echo "$giorno $nome_mese $anno"
}