#!/bin/bash

# ----------------------------------------------------------------------------------- #
# A partire da un id_canto, questo script restituisce il testo del canto a schermo.
# Questa funzione è usata da build_hai_attachment.
# Argomenti:
# - $1 id del canto (int). vd. data/anagrafica_canti.csv
# - $2 path alla cartella con i testi dei canti
# Esempio:
# get_local_text_by_id_canti 2237 risorse/canti
# ----------------------------------------------------------------------------------- #

get_local_text_by_id_canti()
{
    # check $1 and $2 not empty
    if [ -z "$1" ] || [ -z "$2" ]; then
        echo "Error: missing input"
        echo "Usage: get_local_text_by_id_canti <id_canto> <path_to_lyrics_folder>"
        echo "Example: get_local_text_by_id_canti 2237 risorse/canti"
        return 1
    fi

    # build filename using this logic $path_to_lyrics_folder/$id_canto.txt
    filename=$2/$1.txt

    # if $path_to_lyrics_folder/$id_canto.txt does not exist, return error
    if [ ! -f "$filename" ]; then
        echo "Error: File $filename not found"
        return 1
    fi

    # display the content of $path_to_lyrics_folder/$id_canto.txt
    cat $filename
}