#!/bin/bash

# this script will build the md page for the site
# this script is called by build.sh and the variables are shared

# import variables
# source <(grep = scripts/config.ini)


# copy template to output file
cp $PATH_TEMPLATE $PATH_HOMEPAGE

# replace date placeholder with current date
sed -i "s#$PLACEHOLDER_DATE#$liturgia_weekday $liturgia_data_estesa#g" $PATH_HOMEPAGE


# create archive file
# ARCHIVE_FILE_PATH="docs/archive/$liturgia_data_estesa.md"

# replace url liturgia cei placeholder with url liturgia cei
sed -i "s#$PLACEHOLDER_URL_CEI#$URL_LITURGIA_CEI$liturgia_data_yyyymmdd#g" $PATH_HOMEPAGE

# compile rest of the page (tables with suggested songs)
mlr --c2m cat $PATH_DATA_TOP20 >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

echo "Di seguito i canti suggeriti per i vari momenti della liturgia" >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

echo "### Ingresso" >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE
mlr --c2m cat $PATH_DATA_INGRESSO >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

echo "### Offertorio" >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE
mlr --c2m cat $PATH_DATA_OFFERTORIO >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

echo "### Comunione" >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE
mlr --c2m cat $PATH_DATA_COMUNIONE >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

echo "### Congedo" >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE
mlr --c2m cat $PATH_DATA_CONGEDO >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

# add note
echo "## Note" >> $PATH_HOMEPAGE
echo '!!! warning "Attenzione"' >> $PATH_HOMEPAGE
echo "    I canti suggeriti sono stati selezionati automaticamente nelle modalità descritte nella [pagina del progetto](https://hildegard.it/progetto/) e potrebbero non essere adeguati. Si consiglia di verificare la loro aderenza al contesto liturgico." >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

echo '!!! info "Testi"' >> $PATH_HOMEPAGE
echo "    I testi dei canti sono stati tratti da [librettocanti.it](https://www.librettocanti.it/)." >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE
echo "" >> $PATH_HOMEPAGE

