#!/bin/bash

# this script will build the md page for the site

# constants
OUTPUT_FILE_PATH="docs/index.md"
TEMPLATE_PATH="useful-files/template-suggerimenti-latest.md"
LITURGIA_PATH="risorse/lezionari/liturgia-latest.txt"
TOP20_DATA_PATH="data/suggeriti-top20-latest.csv"
INGRESSO_DATA_PATH="data/suggeriti-ingresso-latest.csv"
OFFERTORIO_DATA_PATH="data/suggeriti-offertorio-latest.csv"
COMUNIONE_DATA_PATH="data/suggeriti-comunione-latest.csv"
CONGEDO_DATA_PATH="data/suggeriti-congedo-latest.csv"
URL_CEI_PLACEHOLDER="{{{URL_LITURGIA_CEI}}}"
DATE_PLACEHOLDER="{{{DATA_LITURGIA}}}"
TESTO_LITURGIA_PLACEHOLDER="{{{TESTO_LITURGIA}}}"

# copy template to output file
cp $TEMPLATE_PATH $OUTPUT_FILE_PATH

# replace date placeholder with current date
sed -i "s#$DATE_PLACEHOLDER#$liturgia_weekday $liturgia_data_estesa#g" $OUTPUT_FILE_PATH

# replace testo liturgia placeholder with liturgia text
#testo_liturgia=$(cat $LITURGIA_PATH)
#echo $testo_liturgia
# testo_liturgia=$(echo "$testo_liturgia" | tr '\n' ' ')
#sed -i "s#$TESTO_LITURGIA_PLACEHOLDER#$testo_liturgia#g" $OUTPUT_FILE_PATH

# create archive file
# ARCHIVE_FILE_PATH="docs/archive/$liturgia_data_estesa.md"

# replace url liturgia cei placeholder with url liturgia cei
sed -i "s#$URL_CEI_PLACEHOLDER#$LITURGIA_URL$(date -d $LITURGIA_DATE +%Y%m%d)#g" $OUTPUT_FILE_PATH

# compile rest of the page (tables with suggested songs)
mlr --c2m cat $TOP20_DATA_PATH >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

echo "Di seguito i canti suggeriti per i vari momenti della liturgia" >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

echo "### Ingresso" >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH
mlr --c2m cat $INGRESSO_DATA_PATH >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

echo "### Offertorio" >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH
mlr --c2m cat $OFFERTORIO_DATA_PATH >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

echo "### Comunione" >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH
mlr --c2m cat $COMUNIONE_DATA_PATH >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

echo "### Congedo" >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH
mlr --c2m cat $CONGEDO_DATA_PATH >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

# add note
echo "## Note" >> $OUTPUT_FILE_PATH
echo '!!! warning "Attenzione"' >> $OUTPUT_FILE_PATH
echo "    I canti suggeriti sono stati selezionati automaticamente nelle modalità descritte nella [pagina del progetto](https://hildegard.it/progetto/) e potrebbero non essere adeguati. Si consiglia di verificare la loro aderenza al contesto liturgico." >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

echo '!!! info "Testi"' >> $OUTPUT_FILE_PATH
echo "    I testi dei canti sono stati tratti da [librettocanti.it](https://www.librettocanti.it/)." >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH
echo "" >> $OUTPUT_FILE_PATH

