#!/bin/bash

# constants
ANAGRAFICA_FILE="data/anagrafica_canti.csv"
IDS_FILE="data/id_canti.txt"
CANTI_DIR="canti"

# importa funzioni
source ./scripts/get_text_from_id
source ./scripts/get_anagrafica

# controlla se esiste il file anagrafica 
if [ ! -f $ANAGRAFICA_FILE ]; then
   echo "File $ANAGRAFICA_FILE non trovato! Lo sto scaricando..."
   get_anagrafica > ANAGRAFICA_FILE
fi

# se la cartella canti non esiste, creala
if [ ! -d $CANTI_DIR ]; then
   mkdir $CANTI_DIR
fi

# aggiorna l'anagrafica
get_anagrafica > $ANAGRAFICA_FILE

# usa mlr per estrarre solo la colonna id_canti
mlr --csv cut -f id_canti $ANAGRAFICA_FILE | tail -n +2 | sed 's/"//g' > $IDS_FILE

# per ogni id_canto, usa get_text_from_id per estrarre il testo e salvarlo in CANTI_DIR con nomefile id_canto.txt
total_lines=$(wc -l < $IDS_FILE)
current_line=1

echo "Ho trovato $total_lines canti da scaricare. Inizio il download..."

while read id_canto; do
   get_text_from_id $id_canto > $CANTI_DIR/$id_canto.txt
   echo "Progresso: $current_line/$total_lines"
   ((current_line++))
done < $IDS_FILE

# rimuovi file temporanei
rm $IDS_FILE

# fine
echo "Finito!"