#!/bin/bash

# This script downloads the manually selected songs from the google sheet and saves it to a csv file.

# import the environment variables
source <(grep -e PATH_MANUALLY_SELECTED -e URL_MANUALLY_SELECTED scripts/config.ini)

echo "⚙️ Downloading manually selected songs from the google sheet..."

# check if variables are set
if [ -z "$PATH_MANUALLY_SELECTED" ] || [ -z "$URL_MANUALLY_SELECTED" ]; then
   echo "❌ The PATH_MANUALLY_SELECTED or URL_MANUALLY_SELECTED variable is not set in the config.ini file" >&2
   exit 1
fi

# download and save
curl -skL $URL_MANUALLY_SELECTED \
| mlr --csv cut -f id_canti,id_liturgia,accuratezza,note then filter -S '$id_canti!=""' > $PATH_MANUALLY_SELECTED

# end
echo "✅ Manually selected songs downloaded"
echo "📄 The songs are saved in $PATH_MANUALLY_SELECTED"
