#!/bin/bash

API="https://www.librettocanti.it/api/get_canti"

# funzione get_anagrafica che in output torna un csv
get_anagrafica() {
    curl -skL $API \
    | jq "[.data[] | {id_canti, titolo, autore, raccolta, momento, link_youtube}]" \
    | mlr --j2c cat
}