#!/bin/bash

# get_liturgia wants 3 input
# 1. date in the format YYYY-MM-DD (e.g., 2024-06-02)
# 2. $path_calendario_liturgico
# 3. $path_liturgie

# output of the function
# liturgy text on terminal stdout

check_liturgia_date(){
        # check if the input is provided
    if [ -z "$1" ]; then
        echo "Please provide the date in the format YYYY-MM-DD (e.g. $0 2024-06-02)"
        return 1
    fi

    # check if the input is a valid iso date
    if ! date -d $1 > /dev/null 2>&1; then
        echo "Please provide a valid date in the format YYYY-MM-DD (e.g., $0 2024-06-02)"
        return 1
    fi
    
}

# transform the code into a function get_liturgia
get_liturgia() {

    # check if all the inputs are provided
    if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
        echo "Please provide the date in the format YYYY-MM-DD (e.g. $0 2024-06-02)"
        echo "Please provide the path to the calendario liturgico csv file"
        echo "Please provide the path to the liturgie folder"
        return 1
    fi

    path_calendario_liturgico=$2
    path_liturgie=$3

    check_liturgia_date $1

    # if check fails, return 1
    if [ $? -eq 1 ]; then
        return 1
    fi

    liturgia_data_iso=$1

    # filtra con miller usando $liturgia_data_iso come data
    id_liturgia=$(mlr --csv filter '$date == "'"$liturgia_data_iso"'"' $path_calendario_liturgico | mlr --csv cut -f id_liturgia | mlr --c2n cat)

    # display text and remove more than one empty line
    cat $path_liturgie/$id_liturgia.txt | sed '/^$/N;/^\n$/D'

}



