#!/bin/bash

# constants
LITURGIA_URL="https://www.chiesacattolica.it/liturgia-del-giorno/?data-liturgia=$1"

# concatenate the LITURGIA_URL with the date
# LITURGIA_URL="$LITURGIA_URL$1"

# curl -sL $LITURGIA_URL \
# | scrape -be '.bibbiaedu-linked' \
# | sed 's/<p\/>//g' | sed 's/^ *//g' | sed 's/></> </g' | sed 's/<br\/>/ <br\/>/g' \
# | xq  '[.html.body.span[].a | {url:."@href", data_target:."@data-target", text:."#text"}]'7

curl -sL $LITURGIA_URL \
| xq . | grep bibbiaedu
