#!/bin/bash

# This script downloads the manually selected songs from the google sheet and saves it to a csv file.

# input
CSV_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vTJvTs8qJSUfjUWcEsl0u94WgH66Mhvz0aVkN2IbtFgNAQzizlTaMLtin9tcd0AOXqtxTKHcNpfSRyV/pub?gid=598014936&single=true&output=csv"

# output
OUTPUT_PATH="data/manually_selected.csv"

# download and save
curl -kL $CSV_URL > $OUTPUT_PATH

