#!/bin/bash

# input of the script
# $1 = date in the format YYYYMMDD (e.g., 20240602)

# output of the script
# liturgy text on terminal stdout

# testare anche questo https://www.vaticannews.va/it/vangelo-del-giorno-e-parola-del-giorno/2024/05/26.html

# transform the code into a function get_liturgia
get_liturgia() {

    # constants
    LITURGIA_URL="https://www.chiesacattolica.it/liturgia-del-giorno/?data-liturgia="

    # check if the input is provided
    if [ -z "$1" ]; then
        echo "Please provide the date in the format YYYYMMDD (e.g., $0 20240602)"
        return 1
    fi

    # check if the input is a valid date
    if ! [[ $1 =~ ^[0-9]{8}$ ]]; then
        echo "The date is not in the correct format. Please provide the date in the format YYYYMMDD (e.g., 20240602)"
        return 1
    fi

    # concatenate the LITURGIA_URL with the date
    LITURGIA_URL="$LITURGIA_URL$1"

    # scrape the content of the LITURGIA_URL
    curl -sL $LITURGIA_URL \
    | scrape -be '.cci-liturgia-giorno-section-content' \
    | sed 's/<p\/>//g' | sed 's/^ *//g' | sed 's/></> </g' | sed 's/<br\/>/ <br\/>/g' \
    | xq -r '.. | objects | .["#text"]? // empty'
}
