name: Suggerisco nuovi canti liturgici

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git Credentials
      run: |
        git config user.name "suggeritore-automatico"
        git config user.email "actions@users.noreply.github.com"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
  
    - name: Setup uv
      run: |
        curl -LsSf https://astral.sh/uv/0.5.26/install.sh | sh
        uv venv .venv
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Install dependencies (mlr, scrape, yq, scikit-learn, pandas, tabulate)
      run: |-
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cp bin/scrape ~/bin
        cd ~/bin
        chmod +x mlr
        chmod +x scrape
        uv pip install yq scikit-learn pandas tabulate llm llm-gemini

    - name: Setup llm
      env:
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
      run: |
        echo "$GEMINI_KEY" | llm keys set gemini

    - name: Suggerisci i canti della prossima domenica
      run: |-
        export PATH=$PATH:~/bin
        chmod +x ./build
        ./build
        
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Aggiornati i dati della prossima domenica ${timestamp}" || exit 0
        git push
