name: Aggiorno testi canti

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '0 1 1 * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Enviroment setup (mlr, scrape, yq, scikit-learn, pandas, tabulate)
      shell: bash
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |  
        chmod +x scripts/test_token_cc.sh
        ./scripts/test_token_cc.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "suggeritore-automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Aggiornati i dati della prossima domenica ${timestamp}" || exit 0
        git push
